[package]
name = "proc-sc-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.17"
crossterm = "0.22"
itertools = "0.8.2"
priority-queue = "1.2.1"
indexmap = "1.8.1"
rand = "0.8.5"